config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'graphics#index'
  get 'graphics/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
#Ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
        can :dashboard, :all
        can :access, :rails_admin
        can :read, :dashboard
        can :update, User, id: user.id
        can :manage, Diet
        
        can :manage, GeneralDatum
       #to allow access, you have to put this.
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diet.rb
class Diet < ApplicationRecord
    enum meal: [:breakfast,:snack,:lunch,:dinner,:supper]
end

app/models/general_datum.rb
class GeneralDatum < ApplicationRecord


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :registerable, :rememberable, :validatable
   
    enum kind:[:user, :admin]
    mount_uploader :photo, PhotoUploader

    
      
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    ENV['RAILS_ADMIN_THEME'] = 'rollincode'
end

app/controllers/graphics_controller.rb
class GraphicsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graphics_helper.rb
module GraphicsHelper
end

app/views/graphics/index.html.erb
<div class="card text-center">
    <div class="card-header">
        <h1>Gráfico de Peso</h1>
    </div>
    <div class="card-body">
        <html>

        <head>
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <script type="text/javascript">
                google.charts.load('current', {
                    'packages': ['corechart']
                });
                google.charts.setOnLoadCallback(drawChart);

                function drawChart() {
                    var data = google.visualization.arrayToDataTable([
                        ['Year', 'Peso', 'Peso Ideal'],
                        ['2012', 10, 40],
                        ['2014', 110, 40],
                        ['2018', 130, 40],
                        ['2020', 1030, 540]
                    ]);

                    var options = {
                        title: 'Performa da sua Dieta',
                        hAxis: {
                            title: 'Período',
                            titleTextStyle: {
                                color: '#333'
                            }
                        },
                        vAxis: {
                            minValue: 0
                        }
                    };

                    var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
                    chart.draw(data, options);
                }
            </script>
        </head>

        <body>
            <div id="chart_div" style="width: 100%; height: 500px;"></div>
        </body>

        </html>

        <%= link_to rails_admin_path do %>
        <%= content_tag :span, "cadastro de dieta", :class => "btn btn-primary" %>
        <% end %>

    </div>
    <div class="card-footer text-muted">
        2 days ago
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>DietaMaida</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>



</head>
<!-- FusionCharts Library -->
<script type="text/javascript" src="//cdn.fusioncharts.com/fusioncharts/latest/fusioncharts.js"></script>
<script type="text/javascript" src="//cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.fusion.js"></script>
<script type="text/javascript" src="//cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.gammel.js"></script>
<script type="text/javascript" src="//cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.zune.js"></script>
<script type="text/javascript" src="//cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.carbon.js"></script>
<script type="text/javascript" src="//cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.ocean.js"></script>
</head>

<body style="font-family:'Helvetica Neue', Arial; font-size: 16px;">

    <body>
        <%= yield %>
    </body>
    <%

    def getChart

        # Chart appearance configuration
        chartAppearancesConfigObj = Hash.new
        chartAppearancesConfigObj = {
                        "caption" => "Countries With Most Oil Reserves [2017-18]",
                        "subCaption" => "In MMbbl = One Million barrels",
                        "xAxisName" => "Country",
                        "yAxisName" => "Reserves (MMbbl)",
                        "numberSuffix" => "K",
                        "theme" => "fusion"
                    }

        # An array of hash objects which stores data
        chartDataObj = [
                    {"Venezuela" => "290"},
                    {"Saudi" => "260"},
                    {"Canada" => "180"},
                    {"Iran" => "140"},
                    {"Russia" => "115"},
                    {"UAE" => "100"},
                    {"US" => "30"},
                    {"China" => "30"}
                ]

        # Chart data template to store data in "Label" & "Value" format
        labelValueTemplate = "{ \"label\": \"%s\", \"value\": \"%s\" },"

        # Chart data as JSON string
        labelValueJSONStr = ""

        chartDataObj.each {|item|
            data = labelValueTemplate % [item.keys[0], item[item.keys[0]]]
            labelValueJSONStr.concat(data)
        }

        # Removing trailing comma character
        labelValueJSONStr = labelValueJSONStr.chop

        # Chart JSON data template
        chartJSONDataTemplate = "{ \"chart\": %s, \"data\": [%s] }"

        # Final Chart JSON data from template
        chartJSONDataStr = chartJSONDataTemplate % [chartAppearancesConfigObj.to_json, labelValueJSONStr]

        # Chart rendering
        chart = Fusioncharts::Chart.new({
                width: "600",
                height: "400",
                type: "column2d",
                renderAt: "chartContainer",
                dataSource: chartJSONDataStr
            })

    end
%>

</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>